Update README.md
v1.1 Update

Big update to the code. I am still learning things here. 

Combined the marker and hologram checks into single loops to improve efficiency.
Fixed the multiple definitions of the Holograms function.
Used loop variables for all distance checks and marker drawing.
Ensured distance checks are performed once per frame per blip.
Optimize Citizen.Wait(0)
Combine Threads instead of one per each operation.
Fixed Config issue where you had to create another function for each new location (n00b)...